# Generated by Django 4.1 on 2022-09-09 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_remove_usuario_id_alter_usuario_user'),
        ('roles', '0004_rename_permission_permiso_rename_role_rol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('Planificacion', 'Planificacion'), ('En ejecucion', 'En ejecucion'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Planificacion', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roles.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
            ],
        ),
    ]
