# Generated by Django 4.1 on 2022-09-08 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_rename_permission_permiso_rename_role_rol_and_more'),
        ('usuarios', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='scrum_master',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('Planificacion', 'Planificacion'), ('En ejecucion', 'En ejecucion'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Planificacion', max_length=25),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roles.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
            ],
        ),
    ]
