# Generated by Django 4.1 on 2022-09-09 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_id_alter_usuario_user'),
        ('roles', '0004_rename_permission_permiso_rename_role_rol_and_more'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='roles.rol'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario'),
        ),
    ]
