# Generated by Django 4.1 on 2022-09-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0008_permiso_es_admin'),
        ('proyectos', '0002_alter_miembro_rol_alter_miembro_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembro',
            name='rol',
        ),
        migrations.AddField(
            model_name='miembro',
            name='rol',
            field=models.ManyToManyField(blank=True, null=True, to='roles.rol'),
        ),
    ]
