# Generated by Django 4.1 on 2022-09-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0008_permiso_es_admin'),
        ('proyectos', '0003_remove_miembro_rol_miembro_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='rol',
            field=models.ManyToManyField(blank=True, to='roles.rol'),
        ),
    ]
