# Generated by Django 4.1 on 2022-10-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_alter_miembro_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='capacidad',
            field=models.IntegerField(default=0),
        ),
    ]
