# Generated by Django 4.1 on 2022-10-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0011_remove_userstory_usuario'),
        ('proyectos', '0006_miembro_userstory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembro',
            name='userstory',
        ),
        migrations.AddField(
            model_name='miembro',
            name='userstory',
            field=models.ManyToManyField(blank=True, null=True, to='userstory.userstory'),
        ),
    ]
