# Generated by Django 4.1 on 2022-11-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0004_userstory_campo_alter_userstory_descripcion_and_more'),
        ('proyectos', '0006_miembro_userstory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembro',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='miembro',
            name='userstory',
        ),
        migrations.AddField(
            model_name='miembro',
            name='userstory',
            field=models.ManyToManyField(blank=True, to='userstory.userstory'),
        ),
    ]
