# Generated by Django 4.1 on 2022-11-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_remove_miembro_capacidad_remove_miembro_userstory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
