# Generated by Django 4.1 on 2022-12-14 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_id_alter_usuario_user'),
        ('proyectos', '0008_alter_proyecto_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('accion', models.CharField(choices=[('Creacion', 'Creacion'), ('Modificacion', 'Modificacion'), ('Eliminacion', 'Eliminacion'), ('Importacion', 'Importacion')], max_length=25, null=True)),
                ('elemento', models.CharField(choices=[('Proyectos', 'Proyectos'), ('Roles', 'Roles'), ('Sprints', 'Sprints'), ('Tableros', 'Tableros'), ('Tipo de US', 'Tipo de US'), ('User Stories', 'User Stories')], max_length=25, null=True)),
                ('informacion', models.TextField(null=True)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
            ],
        ),
    ]
