# Generated by Django 4.1 on 2022-10-29 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_alter_miembro_userstory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembro',
            name='capacidad',
        ),
    ]
