# Generated by Django 4.1 on 2022-12-11 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_id_alter_usuario_user'),
        ('proyectos', '0012_historial_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario'),
        ),
    ]
