# Generated by Django 4.1 on 2022-12-14 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0019_userstory_fecha_modificacion_and_more'),
        ('proyectos', '0014_proyecto_story_points_alter_historial_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='userstory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userstory.userstory'),
        ),
    ]
