# Generated by Django 4.1 on 2022-12-16 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_id_alter_usuario_user'),
        ('proyectos', '0016_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='visto',
            field=models.BooleanField(default=False),
        ),
    ]
