# Generated by Django 4.1 on 2022-10-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_us', '0002_miembrotipous'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_us',
            name='campos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
