# Generated by Django 4.1 on 2022-10-16 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0004_alter_miembro_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('duracion', models.PositiveIntegerField(null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('capacidad', models.PositiveIntegerField(null=True)),
                ('estado', models.CharField(choices=[('Planificacion', 'Planificacion'), ('En ejecucion', 'En ejecucion'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Planificacion', max_length=25)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
            ],
        ),
    ]
