# Generated by Django 4.1 on 2022-11-02 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0004_userstory_campo_alter_userstory_descripcion_and_more'),
        ('proyectos', '0007_remove_miembro_capacidad_remove_miembro_userstory_and_more'),
        ('sprints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desarrollador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad_por_dia', models.IntegerField(default=0)),
                ('capacidad_total', models.IntegerField(default=0)),
                ('miembro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.miembro')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprints.sprint')),
                ('userstory', models.ManyToManyField(blank=True, to='userstory.userstory')),
            ],
        ),
    ]
