# Generated by Django 4.1 on 2022-10-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
