# Generated by Django 4.1 on 2022-10-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0003_desarrollador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desarrollador',
            old_name='capacidad',
            new_name='capacidad_por_dia',
        ),
        migrations.AddField(
            model_name='desarrollador',
            name='capacidad_total',
            field=models.IntegerField(default=0),
        ),
    ]
