# Generated by Django 4.1 on 2022-12-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0004_rename_capacidad_desarrollador_capacidad_por_dia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='story_points',
            field=models.IntegerField(default=0),
        ),
    ]
