# Generated by Django 4.1 on 2022-12-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0005_sprint_story_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='horas_aprobadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sprint',
            name='story_points_iniciales',
            field=models.IntegerField(default=0),
        ),
    ]
