# Generated by Django 4.1 on 2022-10-16 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo_us', '0003_tipo_us_campos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campos', models.TextField(default='Pendiente,En curso,Terminado')),
                ('tipo_us', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tipo_us.miembrotipous')),
            ],
        ),
    ]
