# Generated by Django 4.1 on 2022-08-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('nombreUsuario', models.CharField(max_length=100)),
                ('contrasenha', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('fecha_nac', models.DateField()),
                ('capacidadTrabajo', models.IntegerField()),
            ],
        ),
    ]
