# Generated by Django 4.1 on 2022-09-04 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rol',
            new_name='Role',
        ),
    ]
