# Generated by Django 4.1 on 2022-09-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_rename_rol_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
