# Generated by Django 4.1 on 2022-09-05 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_alter_role_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permission',
            new_name='Permiso',
        ),
        migrations.RenameModel(
            old_name='Role',
            new_name='Rol',
        ),
        migrations.RenameField(
            model_name='permiso',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='permission',
            new_name='permiso',
        ),
    ]
