# Generated by Django 4.1 on 2022-09-25 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_alter_miembro_rol_alter_miembro_usuario'),
        ('roles', '0004_rename_permission_permiso_rename_role_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='proyectos.proyecto'),
        ),
    ]
