# Generated by Django 4.1 on 2022-09-26 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_alter_miembro_rol_alter_miembro_usuario'),
        ('roles', '0004_rename_permission_permiso_rename_role_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='es_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
