# Generated by Django 4.1 on 2022-09-25 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_alter_miembro_rol_alter_miembro_usuario'),
        ('roles', '0006_alter_rol_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto'),
        ),
    ]
