# Generated by Django 4.1 on 2022-09-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0007_alter_rol_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='es_admin',
            field=models.BooleanField(default=False),
        ),
    ]
