# Generated by Django 4.1 on 2022-11-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0009_alter_rol_permiso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='permiso',
            field=models.ManyToManyField(blank=True, to='roles.permiso'),
        ),
    ]
