# Generated by Django 4.1 on 2022-09-26 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo_us', '0001_initial'),
        ('proyectos', '0004_alter_miembro_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('horas_estimadas', models.PositiveIntegerField(null=True)),
                ('user_point', models.PositiveIntegerField(null=True)),
                ('business_value', models.PositiveIntegerField(null=True)),
                ('autor', models.TextField(null=True, verbose_name='usuarios.Usuario')),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
                ('tipo_us', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipo_us.tipo_us')),
            ],
        ),
    ]
