# Generated by Django 4.1 on 2022-10-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='sprint_previo',
            field=models.BooleanField(default=False),
        ),
    ]
