# Generated by Django 4.1 on 2022-10-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0002_userstory_sprint_previo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='prioridad',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='sprint_previo',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
