# Generated by Django 4.1 on 2022-10-17 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0002_userstory_prioridad_userstory_sprint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstory',
            name='usuario',
        ),
    ]
