# Generated by Django 4.1 on 2022-11-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0003_remove_userstory_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='campo',
            field=models.TextField(default='Pendiente'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='prioridad',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
