# Generated by Django 4.1 on 2022-10-12 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_us', '0002_miembrotipous'),
        ('userstory', '0003_userstory_prioridad_alter_userstory_sprint_previo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='tipo_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipo_us.miembrotipous'),
        ),
    ]
