# Generated by Django 4.1 on 2022-10-12 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_id_alter_usuario_user'),
        ('userstory', '0004_alter_userstory_tipo_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario'),
        ),
    ]
