# Generated by Django 4.1 on 2022-10-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0005_alter_userstory_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='autor',
            field=models.TextField(null=True),
        ),
    ]
