# Generated by Django 4.1 on 2022-11-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0005_rename_campo_userstory_estado_userstory_asignado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
