# Generated by Django 4.1 on 2022-10-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0006_alter_userstory_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='sprint_previo',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
