# Generated by Django 4.1 on 2022-10-14 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_alter_miembro_rol'),
        ('userstory', '0007_alter_userstory_sprint_previo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='proyectos.miembro'),
        ),
    ]
