# Generated by Django 4.1 on 2022-10-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0009_userstory_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='campo',
            field=models.TextField(default='Pendiente'),
        ),
    ]
