# Generated by Django 4.1 on 2022-10-17 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0010_userstory_campo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstory',
            name='usuario',
        ),
    ]
