# Generated by Django 4.1 on 2022-10-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0011_remove_userstory_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='prioridad',
            field=models.FloatField(null=True),
        ),
    ]
