# Generated by Django 4.1 on 2022-10-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0012_alter_userstory_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='prioridad',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
