# Generated by Django 4.1 on 2022-10-27 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0013_alter_userstory_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
