# Generated by Django 4.1 on 2022-11-02 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0009_remove_miembro_capacidad'),
        ('userstory', '0015_userstory_asignado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstory',
            old_name='campo',
            new_name='estado',
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_trabajadas', models.PositiveIntegerField(null=True)),
                ('mensaje', models.TextField(null=True)),
                ('creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.miembro')),
                ('userstory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userstory.userstory')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('mensaje', models.TextField(null=True)),
                ('creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.miembro')),
                ('userstory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userstory.userstory')),
            ],
        ),
    ]
