# Generated by Django 4.1 on 2022-11-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0017_tarea_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
