# Generated by Django 4.1 on 2022-12-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0018_alter_nota_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='fecha_modificacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userstory',
            name='horas_estimadas_original',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
