# Generated by Django 4.1 on 2022-12-14 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0006_sprint_horas_aprobadas_sprint_story_points_iniciales'),
        ('userstory', '0019_userstory_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaAux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('horas_trabajadas', models.PositiveIntegerField(default=0)),
                ('horas_estimadas_diferencia', models.PositiveIntegerField(default=0)),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sprints.sprint')),
            ],
        ),
    ]
